// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adbaepumrkrqdmmgcspq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkYmFlcHVtcmtycWRtbWdjc3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDEzMDcsImV4cCI6MjA2NjgxNzMwN30.PSYpU_w6PfDot8VTkYS12kTN2UP8QQOBzkFDM1vF_qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});